-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-12 10:03:55 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE arguments (
    id         INTEGER NOT NULL,
    name       VARCHAR(400),
    type       VARCHAR(400),
    methodid   INTEGER
);

ALTER TABLE arguments ADD CONSTRAINT arguments_pk PRIMARY KEY ( id );

CREATE TABLE methods (
    methodid     INTEGER NOT NULL,
    serviceid    INTEGER,
    methodname   VARCHAR(400)
);

ALTER TABLE methods ADD CONSTRAINT methods_pk PRIMARY KEY ( methodid );

CREATE TABLE service (
    id        INTEGER NOT NULL,
    name      VARCHAR(400),
    address   VARCHAR(400)
);

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( id );

INSERT INTO service(id, name, address)
VALUES (1, "Money", "api/money");

INSERT INTO methods(methodid, serviceid, methodname)
VALUES (1, 1, "Add");


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              3
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0